### ISSUE TITLE
admin login problem

### ISSUE THREAD

**Issue by bernameger** [Thiritin/open-signage#2]
hello
I can't log in as admin

**Comment by Thiritin** [comment]
Hi @bernameger 

would you be able to share more information? Is it giving you any kind of error message or is it claiming that your credentials are wrong?

Kind regards
Tin

**Comment by bernameger** [comment]
Hello,

When you click on the "Sign In" button, it just refreshes the page, so it doesn't show any warnings and it does not create an admin during the installation. I created an admin account through normal Laravel, but I still cannot log in.

**Comment by bernameger** [comment]
> Hi @bernameger
> 
> would you be able to share more information? Is it giving you any kind of error message or is it claiming that your credentials are wrong?
> 
> Kind regards Tin

Hello,

When you click on the "Sign In" button, it just refreshes the page, so it doesn't show any warnings and it does not create an admin during the installation. I created an admin account through normal Laravel, but I still cannot log in.

**Comment by Thiritin** [comment]
Unfortunately, I have not yet put an installer in,  This as this would be actually practical for a 3rd party trying to run this.

I am unsure on why you are unable to login, there atleast should be a login. 
Have you started the project via laravel sail or  using regular compose? It does make a difference and usually does not properly start if not done trough laravel sail.

Could you share your .env file (remove any secrets) please? I will confirm with our live installation and see what might be the issue there.

**Comment by bernameger** [comment]
> Unfortunately, I have not yet put an installer in, This as this would be actually practical for a 3rd party trying to run this.
> 
> I am unsure on why you are unable to login, there atleast should be a login. Have you started the project via laravel sail or using regular compose? It does make a difference and usually does not properly start if not done trough laravel sail.
> 
> Could you share your .env file (remove any secrets) please? I will confirm with our live installation and see what might be the issue there.

hi thank you for reply, i use compose like the steps you mentioned in the installation description.

.env file;

`APP_NAME=Laravel
APP_ENV=production
APP_KEY=xxxxxxx
APP_DEBUG=false
APP_URL=https://xxxxx

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=xxxxx
DB_USERNAME=xxxx
DB_PASSWORD=xxxxx

BROADCAST_DRIVER=pusher
CACHE_DRIVER=redis
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
PUSHER_HOST=soketi
PUSHER_PORT=6001
PUSHER_SCHEME=http
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="localhost"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

# This is the project in the opensignage /resources/js/Projects folder
VITE_PROJECT_PATH="EF27"

# If set, all screen urls will need ?shared_secret=SHARED_SECRET to be accessed
APP_SHARED_SECRET=""

# Telegram bot will send notifications to this chat
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
`

**Comment by Thiritin** [comment]
I have checked your env and I cannot find the reason for this odd behavior. I have pushed an update to main to update all packages, possily check that you do not have any browser extension blocking the js code. Werily enough the login UI is filament so there is not even any code in this project that could affect this.

Feel to pull and run npm install and composer update on your local installation. Possibly try to use localhost first and see if that works.

```
APP_NAME="Open Signage"
APP_ENV=local
APP_KEY=<redacted>
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=opensignage
DB_USERNAME=opensignage
DB_PASSWORD=opensignage

BROADCAST_DRIVER=pusher
CACHE_DRIVER=redis
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=app-id
PUSHER_APP_KEY=app-key
PUSHER_APP_SECRET=app-secret
PUSHER_HOST=soketi
PUSHER_PORT=6001
PUSHER_SCHEME=http
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME="${APP_NAME}"
VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="localhost"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
VITE_PROJECT_PATH="EF27"

# Used for Kiosk Screen Config & Restart Authentication
APP_SHARED_SECRET=ThisIsASecret

# Telegram bot will send notifications to this chat
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
```

**Comment by Thiritin** [comment]
PS; There are also now commands for user:create and user:change-password prompting you for all information to make creation easier.

**Comment by bernameger** [comment]
Ok thank you, But I still wonder, could it be that the login process is not possible because there is no "Dashboard" page?
I will try to completely uninstall it and reinstall the system in a while.

**Comment by bernameger** [comment]
> PS; There are also now commands for user:create and user:change-password prompting you for all information to make creation easier.

Ok thank you, But I still wonder, could it be that the login process is not possible because there is no "Dashboard" page?
I will try to completely uninstall it and reinstall the system in a while.

**Comment by Thiritin** [comment]
There is no explicit dashboard Page, I.e. ots the default filament Page. But it works, I have it setup on multiple Servers and my local PC. I am confused why you are experiencing these issues..
